version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      -  './mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_MONGO}
    env_file:
      - .env   

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
     - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_NAME_MONGO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD_MONGO}
      ME_CONFIG_MONGODB_URL: mongodb://${USER_NAME_MONGO}:${PASSWORD_MONGO}@localhost:27017/
      ME_CONFIG_BASICAUTH: false
    env_file:
      - .env 

  redis:
    image: redis:latest
    container_name: redis-supermarket
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD}  
      - REDIS_USER=${REDIS_NAME}     
    env_file:
      - .env 
volumes:
  redis-data:
   
     