version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27018:27017
    volumes:
      -  './mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $USER_NAME_MONGO
      MONGO_INITDB_ROOT_PASSWORD: $PASSWORD_MONGO

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
     - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $USER_NAME_MONGO
      ME_CONFIG_MONGODB_ADMINPASSWORD: $PASSWORD_MONGO

      ME_CONFIG_MONGODB_URL: mongodb://$USER_NAME_MONGO:$PASSWORD_MONGO@localhost:27017/
      ME_CONFIG_BASICAUTH: false
     